### ISSUE TITLE
The GH releases have no test db

### ISSUE THREAD

**Issue by panlinux** [maxmind/MaxMind-DB-Reader-python#63]
Even though the 1.5.4 release notes state a test database was added, they are not in the release assets:
```
$ unzip -l v1.5.4.zip |grep mmdb
$ tar tzf v1.5.4.tar.gz | grep mmdb
$ sha256sum v1.5.4.*
dadfb3c19dae3f12d9cfb8ebec41bc3d506c8825527b661f3f19d6c1413ec076  v1.5.4.tar.gz
1c4b32b6589a9ecbcb9960e77a770a91e08c9533305b78a01e32f84e3c495584  v1.5.4.zip
```
The 1.5.4 tarball from https://pypi.debian.net/maxminddb/ has them (same as https://pypi.org/project/maxminddb/#modal-close):
```
$ tar tzf maxminddb-1.5.4.tar.gz | grep mmdb
maxminddb-1.5.4/tests/data/MaxMind-DB-test-metadata-pointers.mmdb
maxminddb-1.5.4/tests/data/bad-data/libmaxminddb/libmaxminddb-offset-integer-overflow.mmdb
maxminddb-1.5.4/tests/data/bad-data/maxminddb-golang/cyclic-data-structure.mmdb
...
$ sha256sum maxminddb-1.5.4.tar.gz
f4d28823d9ca23323d113dc7af8db2087aa4f657fafc64ff8f7a8afda871425b  maxminddb-1.5.4.tar.gz
```

**Comment by oschwald** [comment]
The files on the GitHub release page are generated by GitHub and we have no control over them. GitHub does not appear to add Git submodules to them.

Is there a reason why you want to download the files from GitHub instead of PyPI? If there was a use case, we could potentially upload our own release files to GitHub, which would show up in addition to the archives GitHub generates.

**Comment by panlinux** [comment]
I'm find with downloading from pypi, I just saw this discrepancy and thought it could be a bug in the release process scripts or something like that. There are other differences between both tarballs, and that added to my confusion.

**Comment by oschwald** [comment]
Thanks! I'll close this for now but will reopen if someone does have a use case where they can't use PyPI.
